name: Deploy Firebase Functions

on:
  push:
    branches:
      - master # Change this to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@master
        with:
          name: "credentials.json"
          json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SAAS_TEMPLATE_739EB }}"

      - name: Set environment variable with path to credentials.json
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$(readlink -f credentials.json)" >> $GITHUB_ENV

      - name: Clean install
        run: cd functions && npm ci

      - name: Install Firebase CLI
        run: npm install -g firebase-tools eslint

      - name: Deploy Functions
        run: firebase deploy --only functions --project splitscreen-studio
