name: Deploy Firestore Rules and Indexes
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Firestore Rules and Indexes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SAAS_TEMPLATE_739EB }}
