name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Set up environment variables
        run: |
          echo "NODE_ENV=production" >> .env

          echo "AUTH_API_KEY=AIzaSyDhPOuhIfGz-avDy2ldIjZfJMHvZTohFzI" >> .env
          echo "AUTH_PROJECT_ID=saas-template-739eb" >> .env
          echo "AUTH_COOKIES_SECURE=true" >> .env

          echo "AUTH_COOKIES_SIGNATURE_KEYS=${{ secrets.AUTH_COOKIES_SIGNATURE_KEYS }}" >> .env
          echo "AUTH_CLIENT_EMAIL=${{ secrets.AUTH_CLIENT_EMAIL }}" >> .env
          echo "AUTH_PRIVATE_KEYS=${{ secrets.AUTH_PRIVATE_KEYS }}" >> .env

          echo "NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyDhPOuhIfGz-avDy2ldIjZfJMHvZTohFzI" >> .env
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=saas-template-739eb.firebaseapp.com" >> .env
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=saas-template-739eb" >> .env
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=saas-template-739eb.appspot.com" >> .env
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=919204756186" >> .env
          echo "NEXT_PUBLIC_FIREBASE_APP_ID=1:919204756186:web:9d28d47cec8a8c7c3183e3" >> .env
          echo "NEXT_PUBLIC_FIREBASE_MEASURMENT_ID=G-JE6HW1WGDN" >> .env

      - name: Build
        run: npm run build

      - name: Deploy to Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SAAS_TEMPLATE_739EB }}
          channelId: live
          projectId: saas-template-739eb
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
